(ns hl7-parser-clojure.segments.pid)

(defrecord PID
  [set-id                                                   ; PID-1: ID do conjunto (sequencial para identificar cada PID em uma mensagem)
   patient-id                                               ; PID-2: Identificação do paciente (opcional, frequentemente obsoleto)
   patient-identifier-list                                  ; PID-3: Lista de identificadores do paciente (e.g., números de registro, CPF)
   alternate-patient-id                                     ; PID-4: Identificadores alternativos do paciente (opcional)
   patient-name                                             ; PID-5: Nome do paciente (e.g., "Sobrenome^Nome^Segundo Nome")
   mother-maiden-name                                       ; PID-6: Nome de solteira da mãe do paciente (opcional)
   datetime-of-birth                                        ; PID-7: Data de nascimento do paciente
   administrative-sex                                       ; PID-8: Sexo administrativo do paciente (e.g., "M" para Masculino, "F" para Feminino)
   patient-alias                                            ; PID-9: Apelidos ou nomes alternativos do paciente (opcional)
   race                                                     ; PID-10: Raça do paciente (opcional, e.g., "2106-3" para "Branco")
   address                                                  ; PID-11: Endereço do paciente (e.g., "Rua^Número^Cidade^Estado^CEP^País")
   county-code                                              ; PID-12: Código do condado ou município (opcional)
   phone-number-home                                        ; PID-13: Número de telefone residencial do paciente (opcional)
   phone-number-business                                    ; PID-14: Número de telefone comercial do paciente (opcional)
   primary-language                                         ; PID-15: Linguagem principal do paciente (opcional, e.g., "PT" para Português)
   marital-status                                           ; PID-16: Estado civil do paciente (opcional, e.g., "S" para Solteiro)
   religion                                                 ; PID-17: Religião do paciente (opcional, e.g., "Católico")
   patient-account-number                                   ; PID-18: Número da conta do paciente (opcional)
   ssn-number                                               ; PID-19: Número do CPF ou outro identificador nacional (opcional)
   driver-license-number                                    ; PID-20: Número da carteira de motorista do paciente (opcional)
   mother-identifier                                        ; PID-21: Identificador da mãe do paciente (opcional)
   ethnic-group                                             ; PID-22: Grupo étnico do paciente (opcional, e.g., "2135-2" para "Hispânico")
   birth-place                                              ; PID-23: Local de nascimento do paciente (opcional)
   multiple-birth-indicator                                 ; PID-24: Indicador de nascimento múltiplo (e.g., "Y" para sim, "N" para não)
   birth-order                                              ; PID-25: Ordem de nascimento (opcional, e.g., "1" para primeiro filho)
   citizenship                                              ; PID-26: Cidadania do paciente (opcional, e.g., "BR" para Brasil)
   veterans-military-status                                 ; PID-27: Status de veterano ou militar (opcional)
   nationality                                              ; PID-28: Nacionalidade do paciente (opcional)
   death-datetime                                           ; PID-29: Data e hora do falecimento do paciente (opcional)
   death-indicator                                          ; PID-30: Indicador de falecimento (e.g., "Y" para sim, "N" para não)
   identity-unknown-indicator                               ; PID-31: Indicador de identidade desconhecida (opcional)
   identity-reliability-code                                ; PID-32: Código de confiabilidade da identidade (opcional)
   last-update-datetime                                     ; PID-33: Data e hora da última atualização das informações do paciente (opcional)
   last-update-facility                                     ; PID-34: Unidade ou organização que fez a última atualização (opcional)
   species-code                                             ; PID-35: Código da espécie (opcional, e.g., "Homo sapiens" para humanos)
   breed-code                                               ; PID-36: Código da raça (relevante para registros veterinários)
   strain                                                   ; PID-37: Estirpe ou linhagem (relevante para registros veterinários)
   production-class-code                                    ; PID-38: Código da classe de produção (relevante para registros veterinários)
   tribal-citizenship                                       ; PID-39: Cidadania tribal (opcional)
   ])
